name: Build
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer
          pip install cython==0.29.33

      - name: Build with Buildozer
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev libbz2-dev
          sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev
          sudo apt-get install -y libavcodec-dev libavformat-dev libavutil-dev libswresample-dev libswscale-dev
          sudo apt-get install -y libsamplerate-dev
          sudo apt-get install -y libxml2-dev libxslt-dev
          sudo apt-get install -y ffmpeg

      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build APK
        run: |
          mkdir -p $HOME/.buildozer/android/platform/android-sdk/licenses
          echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > $HOME/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
          buildozer android debug

      - name: Create assets dir
        run: |
          mkdir -p assets
          touch assets/icon.png

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: bin/*.apk
